[package]
name = "convert_temp"
version = "0.1.0"
authors = ["Matthew Mckenney <matthew.t.mckenney@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
